### PR TITLE
Bug fix. Google Track URL Loading.

### PR DESCRIPTION
**Pull request by turner**

### CODE REVIEW

**Comment by jrobinso** [comment]
@turner I'm not sure about the test  "isGoogleURL",  not all Google URLs have drive info, only Google drive urls.   Google cloud storage does not (GCS does not mangle the name either).   Has this been tested with Google Cloud Storage?

**Comment by turner** [comment]
This fix is for a sharable URL used by the "Load Track URL" widget. Are you saying there are other shareable URLs that this does not work for. For completeness, the code for this uses `isGoogleURL` and `getDriveFileInfo`. Note `getDriveFileInfo` triggers presentation of the Google login popup. Not sure if that is relevant here.

**Comment by jrobinso** [comment]
@turner I don't think you can call "getDriveFileInfo" for a Google Cloud Storage url, which will (I think) return true for isGoogleURL.  You'll likely get an error.  Just saying that should be tested (loading a GCS file by URL).

**Comment by jrobinso** [comment]
The Goggle login widget should not be presented for public GCS files,  I think the test isGoogleURL should be refined to isGoogleDriveURL.

**Comment by jrobinso** [comment]
@turner At one time we didn't use a test at that level, we just had a async call to get the filename.   Google Drive files would need to make the API call, but for other URLs the filename could just be parsed from the URL.   Not sure what happened to that.

**Comment by turner** [comment]
@jrobinso i'm unclear on how to proceed here. I thought `isGoogleURL()` was the most likely candidate for use here. 
Fundamentally I need to 1) confirm a path is valid for it's intended use 2) use the path directly or - in the google case - acquire the actual track url (and name, format, etc). Can you tell me which of the various google handling functions you have written I should be using here.

**Comment by jrobinso** [comment]
@turner ```google.isGoogleDrive```,  but this is a regression so I'm not sure what we did before.

**Comment by turner** [comment]
Ok, switching to `isGoogleDrive()` makes shared URLs and Google Cloud Storage URLs work.

**Pull request merged**
